export const FakedataAPi = {
  OurConsultants: [
    {
      id: 1,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-one.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 2,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-two.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 3,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-three.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 4,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-four.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 5,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-one.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 6,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-two.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 7,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-three.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 8,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-four.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 9,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-one.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 10,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-two.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 11,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-three.png",
      time: "45 د",
      price: "100 ر.س",
    },
    {
      id: 12,
      Title: "اسم المستشار هنا",
      revew: 4.5,
      Specialization: "التخصص هنا",
      linkImage: "/assets/images/user-four.png",
      time: "45 د",
      price: "100 ر.س",
    },
  ],
};
